# -*- coding: utf-8 -*-
"""ru_da_faculdade.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PzKKyHaP_a5O9uqIYvhdr-0ClO-M7Pcs
"""

import numpy as np
import matplotlib.pyplot as plt

# ENTRADA DE DADOS
servico = 'RU de Faculdade'
horario_atendimento = '30 minutos entre o 12h e as 12:30h'
total_servidores = 8
chegadas_minuto = [1,3,2,1,1,2,4,5,4,4,
                   5,6,6,4,7,5,7,8,5,5,
                   4,5,4,3,2,3,3,2,4,3,]
tempo_por_atendimento = [1, 2.5, 1.6, 1.2, 1.1, 1.8, 3.6, 4.6, 4.7, 4.2,
                         4.9, 5.5, 5.9, 3.8, 6.6, 5, 6.9, 7.5, 4.5, 4.3,
                         3.5, 4.9, 4, 2.6, 1.8, 2.5, 3, 1.7, 3.6, 2,4]
# CALCULOS
lambd =  sum(chegadas_minuto) / len(chegadas_minuto)
tempo_medio_atendimento = sum(tempo_por_atendimento) / len(tempo_por_atendimento)
mi = 1/ tempo_medio_atendimento
rho = lambd / (total_servidores * mi)

# SAIDA
print(f'ANÁLISES DE FILA DO SERVIÇO: {servico}')
print(f'HORÁRIO DE ATENDIMENTO: {horario_atendimento} ')
print('---------------------------------------------------')

print('\n\tDADOS COLETADOS')
print(f'Total de chegadas nos 30 minutos:  {sum(chegadas_minuto)}')
print(f'Número de servidores: {total_servidores}')
print(f'Tempo medio de atendimento: {tempo_medio_atendimento}')
print('---------------------------------------------------')

print('\tCALCULOS')
print(f'Taxa de chegada (λ) : {lambd}')
print(f'Taxa de atendimento (μ) : {mi}')
print(f'Taxa de ocupação (ρ) : {rho}')
print('---------------------------------------------------')

print('\tINTERPRETAÇÃO')
if(rho<0.5):
  print('Sistema está subutilizado')
  print('Considere reduzir pessoal')
elif(rho>0.5 and rho<0.8):
  print('Sistema está eficiente')
  print('Mantenha a atual configuração do sistema')
elif(rho>0.8 and rho<1):
  print('Sistema está no limite')
  print('Adicione mais funcionarios')
else:
  print('Sistema está em colapso')
  print('Precisa-se urgentemente de novos funcionarios')
print('---------------------------------------------------')

# GRAFICOS
print('\tGRAFICOS')

plt.figure(figsize=(8, 3))
plt.subplot(1, 2, 1)
plt.bar(range(len(chegadas_minuto)), chegadas_minuto, color='skyblue')
plt.title('Chegadas por Minuto')
plt.xlabel('Minuto')
plt.ylabel('Número de Chegadas')

bins = np.arange(0, 12, 1)

plt.subplot(1, 2, 2)
plt.hist(tempo_por_atendimento, bins=bins, color='lightcoral', edgecolor='black', alpha=0.7)
plt.title('Distribuição do Tempo de Atendimento', fontsize=14)
plt.xlabel('Tempo de Atendimento (minutos)', fontsize=12)
plt.ylabel('Frequência', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()