/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testeString;

/**
 *
 * @author laboratorio
 */
public class PequisaDigital extends javax.swing.JFrame {

    /**
     * Creates new form PequisaDigita
     */
    public PequisaDigital() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txa_res = new javax.swing.JTextArea();
        lbl_caractere = new javax.swing.JLabel();
        lbl_palavras = new javax.swing.JLabel();
        lbl_frase = new javax.swing.JLabel();
        lbl_pesquisa = new javax.swing.JLabel();
        txt_frase = new javax.swing.JTextField();
        txt_pesquisa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_totalCaracteresLocalizados = new javax.swing.JTextField();
        txt_caracteres = new javax.swing.JTextField();
        txt_totalPalavra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txa_res.setEditable(false);
        txa_res.setColumns(20);
        txa_res.setRows(5);
        jScrollPane1.setViewportView(txa_res);

        lbl_caractere.setText("Total de caracteres");

        lbl_palavras.setText("Total de palavras :");

        lbl_frase.setText("Frase :");

        lbl_pesquisa.setText("Pesquisa :");

        txt_frase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fraseKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_fraseKeyReleased(evt);
            }
        });

        jLabel1.setText("Caracteres :");

        txt_totalCaracteresLocalizados.setEditable(false);

        txt_caracteres.setEditable(false);

        txt_totalPalavra.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_totalCaracteresLocalizados))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_pesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_pesquisa))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_frase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_frase))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_palavras)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_totalPalavra))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_caractere)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_caracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_frase)
                    .addComponent(txt_frase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_pesquisa)
                    .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_totalCaracteresLocalizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_caractere)
                    .addComponent(txt_caracteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_palavras)
                    .addComponent(txt_totalPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_fraseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fraseKeyPressed
    }//GEN-LAST:event_txt_fraseKeyPressed

    private void txt_fraseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fraseKeyReleased
        StringBuffer frase;
        if(evt.getKeyCode() == 10){
            frase = new StringBuffer(txt_frase.getText());
            historico.append(frase.toString().toUpperCase()).append("\n");
            txt_frase.setText(historico.toString());
            txt_frase.setText("");
        }else{
            frase = new StringBuffer(txt_frase.getText());
            txa_res.setText(historico.toString() + frase.toString().toUpperCase());
        }
        
        
        txt_caracteres.setText(""+txa_res.getText().length());
        
        txt_totalPalavra.setText(""+contarPalavras(new StringBuffer(txa_res.getText())));
        
        
    }//GEN-LAST:event_txt_fraseKeyReleased

    private int contarPalavras(StringBuffer texto){
        String ts = texto.toString().replace('\n', ' ');
        String vetor[] = ts.split(" ");
        int total = vetor.length;
        return total;
        
        //return texto.toString().split(" ").length;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PequisaDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PequisaDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PequisaDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PequisaDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PequisaDigital().setVisible(true);
            }
        });
    }
 
    StringBuffer historico = new StringBuffer();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_caractere;
    private javax.swing.JLabel lbl_frase;
    private javax.swing.JLabel lbl_palavras;
    private javax.swing.JLabel lbl_pesquisa;
    private javax.swing.JTextArea txa_res;
    private javax.swing.JTextField txt_caracteres;
    private javax.swing.JTextField txt_frase;
    private javax.swing.JTextField txt_pesquisa;
    private javax.swing.JTextField txt_totalCaracteresLocalizados;
    private javax.swing.JTextField txt_totalPalavra;
    // End of variables declaration//GEN-END:variables
}
