/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author thiag
 */
public class MENU extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MENU.class.getName());

    /**
     * Creates new form MENU
     */
    public MENU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCadProf = new javax.swing.JMenuItem();
        MenuEdiProf = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuCadDisc = new javax.swing.JMenuItem();
        MenuEdiDisc = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuListaProf = new javax.swing.JMenuItem();
        MenuBuscaProf = new javax.swing.JMenuItem();
        MenuListarDisc = new javax.swing.JMenuItem();
        MenuBuscaDisc = new javax.swing.JMenuItem();
        MenuDiscProf = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("SAIR");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Professores");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        menuCadProf.setText("Cadastrar");
        menuCadProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadProfActionPerformed(evt);
            }
        });
        jMenu2.add(menuCadProf);

        MenuEdiProf.setText("Editar/Excluir");
        MenuEdiProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEdiProfActionPerformed(evt);
            }
        });
        jMenu2.add(MenuEdiProf);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Disciplinas");

        MenuCadDisc.setText("Cadastrar");
        MenuCadDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadDiscActionPerformed(evt);
            }
        });
        jMenu3.add(MenuCadDisc);

        MenuEdiDisc.setText("Editar/Excluir");
        MenuEdiDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEdiDiscActionPerformed(evt);
            }
        });
        jMenu3.add(MenuEdiDisc);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Relatórios");

        MenuListaProf.setText("Listar professores");
        MenuListaProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuListaProfActionPerformed(evt);
            }
        });
        jMenu4.add(MenuListaProf);

        MenuBuscaProf.setText("Buscar professor por nome");
        MenuBuscaProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBuscaProfActionPerformed(evt);
            }
        });
        jMenu4.add(MenuBuscaProf);

        MenuListarDisc.setText("Listar disciplinas");
        MenuListarDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuListarDiscActionPerformed(evt);
            }
        });
        jMenu4.add(MenuListarDisc);

        MenuBuscaDisc.setText("Buscar disciplina por nome");
        MenuBuscaDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBuscaDiscActionPerformed(evt);
            }
        });
        jMenu4.add(MenuBuscaDisc);

        MenuDiscProf.setText("Disciplina por professor");
        MenuDiscProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDiscProfActionPerformed(evt);
            }
        });
        jMenu4.add(MenuDiscProf);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadProfActionPerformed
        CadastroProfessor cadProf= new CadastroProfessor();
        cadProf.setVisible(true);
    }//GEN-LAST:event_menuCadProfActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void MenuEdiProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEdiProfActionPerformed
        EditarProfessor edProf= new EditarProfessor();
        edProf.setVisible(true);
    }//GEN-LAST:event_MenuEdiProfActionPerformed

    private void MenuBuscaProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBuscaProfActionPerformed
        FiltroNomeProfessor fnProf= new FiltroNomeProfessor();
        fnProf.setVisible(true);
    }//GEN-LAST:event_MenuBuscaProfActionPerformed

    private void MenuCadDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadDiscActionPerformed
        CadastroDisciplinas cadDisc= new CadastroDisciplinas();
        cadDisc.setVisible(true);
    }//GEN-LAST:event_MenuCadDiscActionPerformed

    private void MenuEdiDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEdiDiscActionPerformed
        EditarDisciplina edDisc = new EditarDisciplina();
        edDisc.setVisible(true);
    }//GEN-LAST:event_MenuEdiDiscActionPerformed

    private void MenuBuscaDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBuscaDiscActionPerformed
        FiltroNomeDisciplina fnDisc = new FiltroNomeDisciplina();
        fnDisc.setVisible(true);
    }//GEN-LAST:event_MenuBuscaDiscActionPerformed

    private void MenuListaProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuListaProfActionPerformed
        ListarProfessores lProf= new ListarProfessores();
        lProf.setVisible(true);
    }//GEN-LAST:event_MenuListaProfActionPerformed

    private void MenuListarDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuListarDiscActionPerformed
        ListarDisciplinas lDisc= new ListarDisciplinas();
        lDisc.setVisible(true);
    }//GEN-LAST:event_MenuListarDiscActionPerformed

    private void MenuDiscProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDiscProfActionPerformed
        FiltroDisciplinaPorProfessor fdProf =  new FiltroDisciplinaPorProfessor();
        fdProf.setVisible(true);
        
    }//GEN-LAST:event_MenuDiscProfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MENU().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuBuscaDisc;
    private javax.swing.JMenuItem MenuBuscaProf;
    private javax.swing.JMenuItem MenuCadDisc;
    private javax.swing.JMenuItem MenuDiscProf;
    private javax.swing.JMenuItem MenuEdiDisc;
    private javax.swing.JMenuItem MenuEdiProf;
    private javax.swing.JMenuItem MenuListaProf;
    private javax.swing.JMenuItem MenuListarDisc;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuCadProf;
    // End of variables declaration//GEN-END:variables
}
