-- TRANSACTION
-- ROLLBACK
-- COMMIT
--SAVE POINT

BEGIN TRAN;
INSERT INTO DEPARTAMENTO (Dnome,Dnumero)
VALUES ('Marketing', 88);

SAVE TRAN dptOK;

INSERT INTO DEPARTAMENTO (Data_inicio_gerente,Dnumero)
VALUES('CONSTRUÇÃO', 99);
ROLLBACK TRAN dptOK;
COMMIT TRANSACTION;

SELECT * FROM DEPARTAMENTO

