USE [master]
GO
CREATE LOGIN [vanessa] WITH PASSWORD=N'123456', DEFAULT_DATABASE=[EMPRESA], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
use [master];
GO
USE [EMPRESA]
GO
CREATE USER [vanessa] FOR LOGIN [vanessa]
GO
USE [EMPRESA]
GO
ALTER ROLE [db_datareader] ADD MEMBER [vanessa]
GO
