USE [master]
GO
CREATE LOGIN [Juca] WITH PASSWORD=N'12345', DEFAULT_DATABASE=[BIBLIOTECA], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
use [master];
GO
USE [BIBLIOTECA]
GO
CREATE USER [Juca] FOR LOGIN [Juca]
GO
USE [BIBLIOTECA]
GO
ALTER ROLE [db_datareader] ADD MEMBER [Juca]
GO


